name: "Test package"

on: [ "push", "pull_request" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn test
      - run: yarn test-junit
      - uses: testspace-com/setup-testspace@v1
        with:
         domain: ${{ github.repository_owner }}
      - name: Push result to Testspace server
        run: |
          testspace ./junit/*.xml
        if: always()
